services:
  frappe-snea:
    image: docker.io/vyogo/erpnext:sne-latest
    ports:
      - "8000:8000"
    volumes:
      - ./apps/my_app2:/home/frappe/frappe-bench/apps/my_app2
    entrypoint: /usr/libexec/s2i/run
